import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import AuthProvider from "@/context/AuthProvider";
import { CartProvider } from "@/context/CartContext";
import Cart from "./components/Cart";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trendy Kicks",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <AuthProvider>
        <CartProvider>
          <body className={inter.className}>
            <div className="relative w-full flex justify-center items-center">
              <NavBar />
            </div>
          
            {children}
           <Toaster position="top-center" />
          </body>
        </CartProvider>
      </AuthProvider>
    </html>
  );
}
